version: 0.2
phases:
  build:
    commands:
      - echo "Starting Maven build"
      - mvn clean package -DskipTests
      - echo "Build completed"
      - ls -la target/  # Debug: list files in target directory
artifacts:
  files:
    - '*.jar'  # Look for JAR files in the base directory (target/)
  base-directory: 'target'
  name: 'my-app-artifacts'
