version: 0.2
phases:
  build:
    commands:
      - mvn clean package  # or your build command
artifacts:
  files:
    - '**/*.jar'  # Specify the JAR file pattern
    - 'target/*.jar'  # Common Maven output location
  base-directory: 'target'  # Optional: specify base directory
